name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}

      - name: Configure
        run: >
          cmake -B build -G Ninja
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build
